title: Crispy cod fingers with wedges & dill slaw

description: >
  A fantastic budget family meal with a crunchy slaw and sweet potato wedges. This easy, crowd pleasing recipe is low-fat and full of fresh flavours

# To place an image below the description in the recipe,
# add a file named header.jpg in the recipe directory

sources: # One or more supported. Remove section if none
  - https://www.bbcgoodfood.com/recipes/crispy-cod-fingers-wedges-dill-slaw

# Category must be one of Breakfast, Lunch, Dinner, or Snacks
category: Dinner
sub_category: Fish # Can be anything

times: # In minutes
  prep: 30
  cook: 40

# TODO: Always do servings for 1 person so it can be calculated
servings: 4

ingredients:
  - name: Sweet potatoes
    amount: 700
    unit: gr
    comment: 3 large. Scrubbed and cut into wedges
  - name: Sunflower oil
    amount: 0.5
    unit: tbsp
  - name: Red cabbage
    amount: 0.25
  - name: Red onion
    amount: 0.5
    comment: Finely sliced
  - name: Cornichons
    amount: 6
    comment: Large, quartered
  - name: Greek yogurt or mayonnaise
    amount: 3
    unit: tbsp
  - name: Dill
    amount: 25
    unit: gr
    comment: finely shopped
  - name: Cod fillets
    amount: 640
    unit: gr
    comment: 4, skimmed
  - name: Eggs
    amount: 2
    comment: Large
  - name: Fresh breadcrumbs
    amount: 100
    unit: gr

nutrition: # per serving
  - name: kcal
    amount: 524
  - name: fat
    amount: 10g
  - name: saturates
    amount: 4g
  - name: carbs
    amount: 65g
  - name: sugars
    amount: 31g
  - name: fibre
    amount: 13g
  - name: protein
    amount: 40g
  - name: salt
    amount: 2.2g

steps:
  - step: Heat oven to 200C/180C fan/gas 6
  - step: In a bowl, toss the wedges with the oil, 1 tsp salt and 1/4 tsp pepper
  - step: Transfer to a baking sheet and roast. Turning halfway through. The wedges should be crisp and golden brown.
    time_min: 25
    time_max: 30
  - step: Meanwhile, make the slaw. Remove the cabbage’s white core and discard. Slice the leaves as finely as possible and put in a large mixing bowl with the onion and cornichons
  - step: In another bowl, combine the yogurt or mayonnaise with the dill and 2 tbsp of the cornichons’ pickling liquid
  - step: Mix the dressing with the other slaw ingredients until everything is well coated, then set aside
  - step: Heat grill to high
  - step: Slice each cod fillet into two or three fingers
  - step: Beat the eggs lightly in a shallow bowl
  - step: Tip the breadcrumbs into a separate bowl with a good pinch of salt and pepper
  - step: Dip each cod finger in the egg and then in the breadcrumbs, and place on an oiled baking sheet
  - step: Grill for 6-7 mins or until cooked through and golden
    time_min: 6
    time_max: 7
  - step: Serve with the crispy wedges and a generous helping of the dill pickle slaw
