title: Halfy's Biryani

description: >
  I wasn't satisifed with most of the veg biryani options out
  there so I ended up writing my own by combining some of them together.

sources:
  - https://www.bbcgoodfood.com/recipes/lamb-biryani
  - https://www.bbcgoodfood.com/recipes/cheats-beetroot-biriyani

category: food

ingredients: 
  - name: Olive Oil
    amount: 1
    unit: ml
  - name: One Diced Onion 
    amount: 1
    unit: ml
  - name: Ginger Paste
    amount: 1
    unit: ml
  - name: 1-2 cloves garlic
    amount: 1
    unit: ml
  - name: Cumin
    amount: 1
    unit: ml
  - name: Curry Paste
    amount: 1
    unit: ml
  - name: Rice
    amount: 1
    unit: ml
  - name: Yogurt
    amount: 1
    unit: ml
  - name: Fresh Coriander 
    amount: 1
    unit: ml
  - name: Vegetable Stock
    amount: 1
    unit: ml
  - name: Cubed Paneer
    amount: 1
    unit: ml
  - name: Chillies
    amount: 1
    unit: ml

steps:
  - step: Cook the vegetables in a little oil, cumin and salt until just a little soft. Set aside
    time: 10 minutes
    image: a.jpg
  - step: Fry the onions on a medium heat for 10 minutes until soft
    time: 10 minutes
  - step: Add the ginger paste, half the garlic and cook for a bit
    time: 1 minute
  - step: Add the veg back and mix in the curry paste
    time: 90 seconds
  - step: Add the rice, stock pot and hot water and bring to the boil
    time: 2 minutes
  - step: Heat the oven to 180C
  - step: Stir in the paneer and spinach until just a little liquid is visible, and season.
  - step: Cover the dish with foil and then a lid. Cook in the oven for 20 minutes.
  - step: Take out from the oven and give it a stir, if some liquid remains then cook on the hob until it's still moist but not very wet.
  - step: Scatter coriander and chillies, and mix in some yougart.
          
