name: github pages

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-18.04
    steps:
      # Build markdown stuff using node index.mjs
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run-script build

      # Build book using mdbook
      - name: mdBook Action
        uses: peaceiris/actions-mdbook@v1.1.13
        with:
          mdbook-version: 'latest'
      - run: mdbook build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
